// Generated by LiveScript 1.2.0
var path, fs, commands;
path = require('path');
fs = require('fs');
commands = module.exports = {};
commands['watch'] = require('./commands/watch');
commands['start'] = require('./commands/start');