// Generated by LiveScript 1.2.0
var fs, path, process, child_process, repl;
fs = require('fs');
path = require('path');
process = require('process');
child_process = require('child_process');
repl = require('repl');
module.exports = function(arg, ge, done){
  var exec, spawn;
  exec = require('child_process').exec;
  spawn = require('child_process').spawn;
  return exec("cargo run", function(err, stdout, stderr){
    console.log(stdout);
  });
};