// Generated by LiveScript 1.2.0
var fs, path, process, child_process, repl, nodeWatch;
fs = require('fs');
path = require('path');
process = require('process');
child_process = require('child_process');
repl = require('repl');
nodeWatch = require('node-watch');
module.exports = function(arg, ge, done){
  var exec, spawn, ctx;
  exec = require('child_process').exec;
  spawn = require('child_process').spawn;
  console.log('*************');
  console.log("Rust Watch: " + process.cwd());
  console.log('*************');
  ctx = repl.start({
    'eval': function(cmd, context, filename, callback){
      var cmdCtx;
      cmdCtx = cmd.split('(')[1].replace('\n)', '');
      return child_process.exec("rust " + cmdCtx, function(err, stdout, stderr){
        console.log(stdout);
        callback();
      });
    },
    prompt: 'rust > ',
    input: process.stdin,
    output: process.stdout
  });
  nodeWatch(process.cwd() + '/src', {
    recursive: false,
    followSymLinks: true
  }, function(filename){
    var child;
    console.log(filename, ' changed.' + '\n');
    child = spawn('cargo', ['build'], {
      stdio: 'inherit'
    });
  });
};